### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by Cascadia-EmilioDiaz** [MobileApps-Cascadia/northcreekforest-app#7]
Desc: Implement QR scanner for Photo-Points

DOD: Scanner successfully scans QR code, with information displaying

Notes: Get a QR code from David Bane to test (Or any code)

**Comment by brinks92** [comment]
Given to Aaron for sprint 2-3

**Comment by Akohler28** [comment]
Comment: Requires field testing in forest on the real QR Codes.
